#!/usr/bin/env bash

hugo -DF
bash code/mathjax
node code/render.js

for i in $*
do
  i=${i#content}
  i=${i%.md}
  src=public/_prince${i}/index.html
  
  pdf=${i##*/}.pdf
  
  prince $src -o $pdf --fileroot=public/
  open $pdf
done
